### ISSUE TITLE
Aniseed has some broken Lua interaction, stopping further development until this is fixed

### ISSUE THREAD

**Issue by katawful** [katawful/kat.nvim#7]
See here: https://github.com/Olical/aniseed/issues/98

Until this is fixed or a workaround is made, I am unable to even push a commit to any branch as it will immediately break Lualine, Airline, and Lightline

**Comment by Olical** [comment]
Oh NO! This is horrible. You can however fix this by doing one of two things:

 1) In modules where you want to return a table, don't return tables from the final position. This means you can return a table and treat it like a vanilla fennel module. The presence of the `(module...)` form indicates to Aniseed that you DON'T want it to use the table returned from the module as the exported value since that leads to subtle bugs.
 2) In the module you're having issues with (https://github.com/katawful/kat.nvim/blob/main/fnl/lualine/themes/kat.fnl) you can replace your table mutation and returning with `(def ...)` calls which basically does that for you within the Aniseed framework.

I hope this is helpful! The "bug" isn't really a bug but a defence against a subtle issue where if someone had the module:

```fennel
(module foo)

(def a 10)

15
```

Then the `foo` module when required would just return `15`! But only if loaded from a Lua file and not run interactively. So this confusing and inconsistent behaviour has been "fixed" but that's come as a breaking change to some who relied on the behaviour 😭 

Now if you opt into `(module ...)` macros you have to use `def` and `defn` to export things rather than returning a table. Or you can opt out and return a table by not using the macros, the thing you can't do any more is mix and match.

**Comment by katawful** [comment]
I will try that. Just for clarity, when I get rid of the module macro from a fennel file, is it best to resort back to the fennel expressions over the equivalent Aniseed macros (ie fn instead of defn) for this case?

**Comment by Olical** [comment]
Yep, so you have to go all or nothing now. I know that might be annoying but it's for a good reason, there were weird bugs cropping up where people were trying to use Aniseed module macros but accidentally returned a truthy value from the bottom of their module leading to nothing they wrote working with no explanation.

So if you remove the `(module ...)` block the `def*` macros will stop working (I think?) so you have to build a table as the module loads then reference it in the tail position of your module.

You can also (I think! Will have to try it) mutate the `*module*` table (written exactly as that in your code), that table is essentially magically returned from your module. So if you REALLY can't convert to `def` macros in that file I linked (I think you can :D) then you can instead do stuff like `(tset *module* :my-key {:some :value})` which will export that value too.

**Comment by katawful** [comment]
Got it to work using just fennel stuff, thanks for the help!
